### PR TITLE
implemented result casting for then and catch

### PR DESCRIPTION
**Pull request by felix-dumit**
Implemented the result casting as we previously discussed in #2 

Sample use:

``` objc
    [BFTask taskWithResult:@"result"].then ( ^id (NSString* result) {
        return nil;
    }).catch ( ^id (NSError* error) {
        return nil;
    }).finally ( ^id (BFTask *task) {
        return nil;
    });
```

I've updated the tests to use this syntax and it's all green.

Sorry I took a while to do this it's been a busy couple weeks.

### CODE REVIEW

**Comment by hironytic** [comment]
Thanks, and sorry for my late reply. But please give me a little more time.

**Comment by hironytic** [comment]
Thanks for your great work!
I made some changes on it. Please check my commits.

**Type Prefix**
To avoid conflict with original Bolt's future implementation, the type prefix is changed from `BF` to `BFP`.
i.e. `BFPSuccessResultBlock`

**Conversion from `NSException` to `NSError`**
The `code` of `NSError` is domain specific. I don't think code 998 is a particularly good idea.
Also I don't think the exception name and the error domain are same one. 
I rewrite to keep `NSException` object directly in `userInfo` dictionary.
But I agree with your idea putting `reason` of `NSException` as a value of `NSLocalizedDescriptionKey`.

**Unused Type**
The type `BFResultBlock` was not used anywhare. I deleted it.

**Comment by felix-dumit** [comment]
I like to changes you added as well. Good job :+1:

**Comment by hironytic** [comment]
I'm happy that you like them.

**Pull request merged**
