### PR TITLE
A block which runs regardless of success or error.

### PR DESCRIPTION
**Pull request by hironytic**
In issue #2, @felix-dumit would want a block to run regardless of success or error.
Since `BFTask` originally has `continueWithBlock:`, I can write a dot-notation wrapper.
Although I don't like the name `thenOrCatch` so much.:confused:
Opinions?

### CODE REVIEW

**Comment by felix-dumit** [comment]
how about .continue() ? Or would that conflict with the continue keyword?

**Comment by hironytic** [comment]
:+1:
Just now, I come up with a same name `continue`.
I'll give it a try later.

**Comment by hironytic** [comment]
Bad news :disappointed: 
`continue` conflicts with Objective-C's keyword.

```
error: expected identifier
[BFTask taskWithResult:@30].continue(^id(BFTask *task){
                            ^
```

Also bad news :scream:
`catch` conflicts with Objective-C++'s keyword.

```
error: expected unqualified-id
    [BFTask cancelledTask].catch(^id(BFTask *task){
                           ^
```

**Comment by felix-dumit** [comment]
How about `.continueWith`, going back to the original BFTask names. Maybe it would need to be `.catchWith` also. I don't know if I really like it though

**Comment by hironytic** [comment]
Yes, you are right.
I'd prefer `continueWith` to `thenOrCatch`.

And for ObjC++, `catchWith` would help.

``` objc
// for Objective-C++
- (BFTask *(^)(BFContinuationBlock))catchWith {
    return [self catch];
}
```

But that would be out of this PR.

**Pull request merged**
